services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: music_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network
    # Test pour vérifier que Postgres est pleinement opérationnel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d music_game"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    networks:
      - internal-network

  cekikilami-backend:
    container_name: cekikilami-backend
    build:
      context: ./backend
    environment:
      PORT: 3001
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres@postgres:5432/music_game
      REDIS_URL: redis://redis:6379
      CORS_ORIGIN: https://cekikilami.lucasspitzer.fr
    depends_on:
      postgres:
        condition: service_healthy # Attend que le healthcheck de Postgres passe au vert
      redis:
        condition: service_started
    networks:
      - internal-network
      - proxy
    restart: on-failure # Redémarre automatiquement en cas de crash imprévu

  cekikilami-frontend:
    container_name: cekikilami-frontend
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://cekikilami.lucasspitzer.fr/api
        VITE_SOCKET_URL: https://cekikilami.lucasspitzer.fr
    depends_on:
      - cekikilami-backend
    networks:
      - internal-network
      - proxy

volumes:
  postgres_data:

networks:
  internal-network:
    driver: bridge
  proxy:
    external: true