events {}

http {
  upstream frontend_upstream {
    server cekikilami-frontend:80;
  }

  upstream backend_upstream {
    server cekikilami-backend:3001;
  }

  server {
    listen 80;

    location /socket.io/ {
      proxy_pass http://backend_upstream/socket.io/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    location /uploads/ {
      proxy_pass http://backend_upstream/uploads/;
      proxy_set_header Host $host;
    }

    location /api/ {
      proxy_pass http://backend_upstream/api/;
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://frontend_upstream;
      proxy_set_header Host $host;
    }
  }
}
